#!/usr/bin/env python

from optparse import OptionParser
import sys

from distributions import b_model_time_series

def die(msg):
    sys.stderr.write('%s' %(msg))
    sys.exit(1)

def main():
    parser = OptionParser()
    parser.add_option('-n', '--nodes',
                      dest = 'nnodes',
                      type = 'int', 
                      default = 10,
                      metavar = 'N',
                      help = 'set number of nodes N')
    parser.add_option('-p', '--write-probability',
                      dest = 'wprob',
                      type = 'float',
                      default = 0.5,
                      metavar = 'P',
                      help = 'set write probability P')
    parser.add_option('-s', '--write-size',
                      dest = 'wsize',
                      type = 'int',
                      default = 1024,
                      metavar = 'S',
                      help = 'set total write size S')
    parser.add_option('-t', '--time',
                      dest = 'ctime',
                      type = 'int',
                      default = 1024,
                      metavar = 'T',
                      help = 'set total computation time T')
    parser.add_option('-x', '--comp-b',
                      dest = 'cb',
                      type = 'float',
                      default = 0.7,
                      metavar = 'b',
                      help = 'set b model value in range [0, 1] for computation time randomization')
    parser.add_option('-y', '--comm-b',
                      dest = 'wb',
                      type = 'float',
                      default = 0.7,
                      metavar = 'b',
                      help = 'set b model value in range [0, 1] for communication size randomization')
    (options, args) = parser.parse_args()

    if options.nnodes <= 0:
        die('Invalid number of nodes: %d\n' %(options.nnodes))
    if options.wprob < 0 or options.wprob > 1:
        die('Invalid write probablity: %f\n' %(options.wprob))
    if options.wsize < 0:
        die('Invalid write size: %d\n' %(options.wsize))
    if options.ctime <= 0:
        die('Invalid write size: %d\n' %(options.ctime))
    if options.cb < 0 or options.cb > 1:
        die('Invalid computation b value: %f\n' %(options.cb))
    if options.wb < 0 or options.wb > 1:
        die('Invalid communication b value: %f\n' %(options.wb))

if __name__ == '__main__':
    main()
